logging:
  level:
    at.fankhauser: DEBUG
  file: logs/${spring.application.name}.log
spring:
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username : postgres
    password : postgres
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
  mvc:
    view:
      prefix : /WEB-INF/jsps/
      suffix : .jsp
  application:
    name: Zeiterfassung