logging:
  level:
    at.fankhauser: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  file: logs/${spring.application.name}.log
spring:
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username : postgres
    password : postgres
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
  application:
    name: Zeiterfassung Backend
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false